
[build]
  command = "npm run build"
  publish = "dist"

# Optimizations for SPA navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTP/2 server push
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' https://images.unsplash.com https://i.pravatar.cc https://*.netlify.app https://lovable.dev data:; font-src 'self' https://fonts.gstatic.com; connect-src 'self';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Link = "</src/index.css>; rel=preload; as=style"
    X-Robots-Tag = "index, follow"

# Optimize critical assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"

# Custom 404 page
[[redirects]]
  from = "*"
  to = "/404.html"
  status = 404
